### ISSUE TITLE
Update lisk_snapshot.sh for latest Lisk release

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk-build#202] opened 2017-10-17 13:48 UTC
I installed Lisk 0.9.9 with liskInstall.sh but seems lisk_snapshot.sh isn't updated, when I try to make snapshot (of course without 'c' parametr) I get this message:
 `Unimplemented option: -c`

**Comment by Isabello** [comment] 2017-10-17 15:07
Closing this one as duplicate. In the future please provide more information and maybe some research. Duplicate of: #205

**Closed as completed by Isabello** 2017-10-17 15:07 UTC
Labels: duplicate
