### ISSUE TITLE
Toolchain script outdated

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-build#285] opened 2018-06-11 09:22 UTC
Currently the build script is failing due to `bash: sponge: command not found`. Found that its part of the `moreutils` package which is not added into the toolchain script.

**Comment by Nazgolze** [comment] 2018-06-11 09:37
Closing because it's a duplicate of #280. This is in progress

**Closed as completed by Nazgolze** 2018-06-11 09:37 UTC
